#pragma config(Sensor, dgtl1,  LED1,              sensorLEDtoVCC)
#pragma config(Sensor, dgtl2,  LED2,              sensorLEDtoVCC)
#pragma config(Sensor, dgtl3,  LED3,              sensorLEDtoVCC)
#pragma config(Sensor, dgtl4,  sonar,          sensorSONAR_cm)
#pragma config(Sensor, dgtl7,  limitSwitch_1,    sensorTouch)
#pragma config(Sensor, dgtl8,  limitSwitch_2,    sensorTouch)
#pragma config(Sensor, dgtl9,  limitSwtich_3,    sensorTouch)
#pragma config(Motor,  port2,           motor1,        tmotorVex393, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*
Start Program
constantly wait at floor 1
if inside button is pushed or if outside button is pushed, go to floor, turn LEDs on once at floor
Use ultrasonic to sense floor height
End Program
*/

void MoveToFloor(int floorNum);								// move elevator to designated floor
void turnLedsOff ();									// turn all LEDs off
void turnOnLed(int ledNum);								// turn on particular LED

task main()
{
	ClearTimer(T1);									// reset timer
	turnLedsOff();									// turn all LEDs off - they are on by default

	if (SensorValue[sonar] != 5)							// if elevator is not already at floor 1
		MoveToFloor(1);								// move to floor 1

	while(1)
	{
		if (time100[T1] > 50)							// check if motor hasn't moved in 5 seconds
			MoveToFloor(1);							// if it hasnt't moved in 5 seconds, move to floor 1
		if (SensorValue[limitSwitch] == 1 					// if inside or outside button 1 is hit
			MoveToFloor(1);							// move to floor 1
		if (SensorValue[limitSwitc] == 1 					// if inside or outside button 2 is hit
			MoveToFloor(2);							// move to floor 2
		if (SensorValue[limitSwitch] == 1 					// if inside or outside button 3 is hit
			MoveToFloor(3);							// move to floor 3
	}
}

void MoveToFloor(int floorNum)
{
	turnLedsOff();								// turn all LEDS off

	if(SensorValue[sonar] > floorNum*5)					// if elevator is higher than desired floor
		while (SensorValue[sonar] != floorNum*5)			// while sonar distance is not at 5 times floor number
		startMotor(motor1, -20);					// move elevator down
	else									// else - elevator is lower than desired floor
		while (SensorValue[sonar] != floorNum*5)			// while sonar distance is not at 5 times floor number
		startMotor(motor1, 20);						// move elevator up

	stopMotor(motor1);							// stop motor

	turnOnLed(floorNum);							// turn on LED based on floor number

	ClearTimer(T1);								// reset timer since elevator moved
}

/* turnLedsOff function turn all LEDS off */
void turnLedsOff ()
{
	turnLEDOff(G);
	turnLEDOff(Y);
	turnLEDOff(R);
}

/* turnOnLed function turns on a specific floor's LEDs*/
void turnOnLed(int ledNum)
{
	switch (ledNum)								// ledNum is floor number
	{
	case 1:									// floor 1
		{
			turnLEDOn(G);						// turn on green LEDs
		}
		break;
	case 2:									// floor 2
		{
			turnLEDOn(Y);						// turn on yellow LEDs
		}
		break;
	case 3:									// floor 3
		{
			turnLEDOn(R);						// turn on red LEDs
		}
		break;
	}
}
